services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  camera-service:
    build: ./camera_service
    container_name: camera-service
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CAMERA_TOPIC: camera_frames
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  processing-service:
    build: ./processing_service
    container_name: processing-service
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CAMERA_TOPIC: camera_frames
      RESULT_TOPIC: detection_results
      YOLO_MODEL: yolov8n.pt
      CONF_THRESHOLD: 0.35
    ports:
      - "8002:8002"
    restart: unless-stopped

  storage-service:
    build: ./storage_service
    container_name: storage-service
    depends_on:
      - kafka
      - mongodb
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      RESULT_TOPIC: detection_results
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB: people_counting
      MONGO_COLLECTION: detections
      SAVE_IMAGE_INTERVAL_SEC: 1
    ports:
      - "8003:8003"
    restart: unless-stopped
    volumes:
      - ./results:/app/results

volumes:
  mongo_data:
